version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - FLASK_APP=src.main
      - FLASK_DEBUG=0
    volumes:
      - ./app.log:/app/app.log
      - ./src/bot.log:/app/src/bot.log
    depends_on:
      - db
    ports:
      - "5000:8080"

  db:
    image: sqlite3
    volumes:
      - sqlite_data:/var/lib/sqlite
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  sqlite_data: 